config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/signup', to: 'devise/registrations#new'
  end

  get '/workouts', to: 'workouts#index', as: :user_root

  resources :users, only: [:show] do
    resources :workouts, only: [:index, :new, :create]
  end

  resources :workouts, only: [:index, :show, :edit, :update, :destroy] do
    resources :user_saved_workouts, only: [:new, :create, :edit, :update, :destroy]
    resources :custom_exercises, only: [:create]
    resources :comments, only: [:create]
  end

  resources :exercises, only: [:show]
  
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user

  has_many :comments, inverse_of: 'workout', dependent: :destroy

  has_many :user_saved_workouts, foreign_key: :saved_workout_id, dependent: :destroy
  has_many :saved_users, through: :user_saved_workouts

  has_many :custom_exercises, dependent: :destroy
  has_many :exercises, through: :custom_exercises

  validates :name, presence: true
  validates :description, presence: true

  accepts_nested_attributes_for :custom_exercises, allow_destroy: true, reject_if: proc { |attrs| attrs['exercise_id'].blank? }

  scope :newest_first, -> { order(created_at: :desc) }
  scope :by_exercise, ->(exercise_name) { joins(:custom_exercises).joins(:exercises).where('exercises.name LIKE ? ', "%#{exercise_name}%").distinct }
  scope :by_user, ->(user_name) { joins(:user).where('users.name LIKE ?', "%#{user_name}%").distinct }

  def comments_by_created_at
    self.comments.includes(:user).order(created_at: :desc)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  def index
    @workout = Workout.new
    @exercises = Exercise.alphabetical
    @users = User.alphabetical
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      if !@user
        redirect_to workouts_path, alert: 'User Not Found' 
      else
        if params[:exercise_name] && params[:exercise_name].present?
          @workouts = @user.workouts.by_exercise(params[:exercise_name])
        else
          @workouts = @user.workouts
        end
      end
    elsif params[:exercise_name].try(:present?) || params[:user_name].try(:present?)
      @workouts = Workout.by_exercise(params[:exercise_name]).by_user(params[:user_name])
    else
      @workouts = Workout.newest_first
    end
  end

  def new
    @exercises = Exercise.alphabetical
    @workout = current_user.workouts.build
    5.times { @workout.custom_exercises.build }
  end

  def create
    @workout = current_user.workouts.build(workout_params)
    if @workout.save
      redirect_to workout_path(@workout)
    else
      @exercises = Exercise.alphabetical
      # 5.times { @workout.custom_exercises.build }
      render :new
    end
  end

  def show
    if !@workout
      flash[:alert] = 'Workout Not Found'
      redirect_to workouts_path
    else
      @custom_exercises = @workout.custom_exercises
      @comment = @workout.comments.build
    end
  end

  def edit
    @exercises = Exercise.alphabetical
    if !@workout
      flash[:alert] = 'Workout Not Found'
      redirect_to workouts_path
    else
      @custom_exercise = CustomExercise.new
    end
  end

  def update
    if @workout.update(workout_params)
      redirect_to workout_path(@workout)
    else
      @exercises = Exercise.alphabetical
      render :edit
    end
  end

  def destroy
    @workout.destroy
    redirect_to user_path(current_user)
  end

  private

  def set_workout
    @workout = Workout.find_by(id: params[:id])
  end

  def workout_params
    params.require(:workout).permit(:name, :description, custom_exercises_attributes: [:id, :_destroy, :exercise_id, :rep_range, :sets])
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def workout_user_name(workout)
    workout.user.name
  end

  def current_users_workout?(workout)
    current_user.workouts.exists?(workout.id)
  end
end

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>

<h2>Add Exercise:</h2>
<%= form_with(model: [@workout, @custom_exercise], local: true) do |f| %>
  <%= f.label :exercise_id %>
  <%= f.collection_select :exercise_id, @exercises, :id, :name, include_blank: true %><br />

  <%= f.label :rep_range, 'Rep Range: (6, 2..5, 8 to 12, etc.)' %>
  <%= f.text_field :rep_range, placeholder: @custom_exercise.errors[:rep_range].to_sentence %><br />

  <%= f.label :sets, 'Sets: ' %>
  <%= f.number_field :sets, placeholder: @custom_exercise.errors[:sets].to_sentence %><br />

  <%= f.submit 'Add Exercise' %>
<% end %>

<h2>Workout: </h2>
<%= form_with(model: @workout, local: true) do |f| %>
  <%= f.label :name, 'Workout Name: ' %>
  <%= f.text_field :name, placeholder: @workout.errors[:name].to_sentence %><br />

  <%= f.label :description, 'Workout Description: ' %>
  <%= f.text_area :description, placeholder: @workout.errors[:description].to_sentence %><br />

  <%= f.fields_for :custom_exercises do |ce_form| %>
    <p>Exercise #<%= ce_form.index + 1 %></p>
    <%= ce_form.label :exercise_id %>
    <%= ce_form.collection_select :exercise_id, @exercises, :id, :name, include_blank: true %><br />

    <%= ce_form.label :rep_range, 'Rep Range: (6, 2..5, 8 to 12, etc.)' %>
    <%= ce_form.text_field :rep_range, placeholder: @workout.errors[:'custom_exercises.rep_range'].to_sentence %><br />

    <%= ce_form.label :sets, 'Sets: ' %>
    <%= ce_form.number_field :sets, placeholder: @workout.errors[:'custom_exercises.sets'].to_sentence %><br />

    <%= ce_form.label :_destroy, 'Delete?' %>
    <%= ce_form.check_box :_destroy %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/workouts/index.html.erb
<h1><%= "#{@user.name}'s " if @user %>Workouts</h1>
<p><%= link_to('View All Workouts', workouts_path) if @user %></p>

<h3>Filter: </h3>
<%= form_with(model: [@user, @workout], method: :get, local: true) do %>
  <%= select_tag :exercise_name, options_from_collection_for_select(@exercises, :name, :name), include_blank: true %>
  <%= select_tag :user_name, options_from_collection_for_select(@users, :name, :name), include_blank: true %>
  <%= submit_tag 'Filter' %>
<% end %>

<ul>
<% @workouts.each do |workout| %>
  <li>
    <h2><%= link_to(workout.name, workout_path(workout), class: 'button') %></h2>
    <p><%= workout.description %></p>
    By: <%= link_to(workout_user_name(workout), user_path(workout.user)) %>
  </li>
<% end %>
</ul>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= form_with(model: [current_user, @workout], local: true) do |f| %>
  <%= f.label :name, 'Workout Name: ' %>
  <%= f.text_field :name, placeholder: @workout.errors[:name].to_sentence %><br />

  <%= f.label :description, 'Workout Description: ' %>
  <%= f.text_area :description, placeholder: @workout.errors[:description].to_sentence %><br />

  <%= f.fields_for :custom_exercises do |ce_form| %>
    <p>Exercise #<%= ce_form.index + 1 %></p>
    <%= ce_form.label :exercise_id %>
    <%= ce_form.collection_select :exercise_id, @exercises, :id, :name, include_blank: true %><br />

    <%= ce_form.label :rep_range, 'Rep Range: (6, 2..5, 8 to 12, etc.)' %>
    <%= ce_form.text_field :rep_range, placeholder: @workout.errors[:'custom_exercises.rep_range'].to_sentence %><br />

    <%= ce_form.label :sets, 'Sets: ' %>
    <%= ce_form.number_field :sets, placeholder: @workout.errors[:'custom_exercises.sets'].to_sentence %><br />
  <% end %>

  <%= f.submit %>
<% end %>

app/views/workouts/show.html.erb
<h1><%= @workout.name %></h1>
<h3>By: <%= link_to(workout_user_name(@workout), user_path(@workout.user)) %></h3>
<%= render partial: 'shared/save_workout' if !current_users_workout?(@workout) %>
<%= link_to('Edit Workout', edit_workout_path(@workout), class: 'small_button') if current_users_workout?(@workout) %>
<%= button_to('Delete Workout', workout_path(@workout), method: :delete, data: { confirm: 'Are you sure?' }) if current_users_workout?(@workout) %>

<ol>
<% @custom_exercises.each do |custom_exercise| %>
  <li>
    <h4><%= link_to(custom_exercise.exercise_name, exercise_path(custom_exercise.exercise)) %>, Reps: <%= custom_exercise.rep_range %>, Sets: <%= custom_exercise.sets %></h4>
  </li>
<% end %>
</ol>

<p><%= @workout.description %></p>

<%= form_with(model: [@workout, @comment], local: true) do |f| %>
  <%= f.text_area :body, placeholder: 'Comment Here...' %><br />
  <%= f.submit %>
<% end %>

<h2>Comments: </h2>
<ul>
<% @workout.comments_by_created_at.each do |comment| %>
  <li><%= link_to(comment_user_name(comment), user_path(comment.user)) %>: <%= comment.body %></li>
<% end %>
</ul>