config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/signup', to: 'devise/registrations#new'
  end

  get '/workouts', to: 'workouts#index', as: :user_root

  resources :users, only: [:show] do
    resources :workouts, only: [:index, :new, :create]
  end

  resources :workouts, only: [:index, :show, :edit, :update, :destroy] do
    resources :user_saved_workouts, only: [:new, :create, :edit, :update, :destroy]
    resources :custom_exercises, only: [:create]
    resources :comments, only: [:create]
  end

  resources :exercises, only: [:show]
  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :workouts
  has_many :comments, inverse_of: 'user', dependent: :destroy

  has_many :user_saved_workouts, foreign_key: :saved_user_id, dependent: :destroy
  has_many :saved_workouts, through: :user_saved_workouts

  validates :name, presence: true

  scope :alphabetical, -> { order(:name) }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_users_profile?(user)
    user == current_user
  end 
end

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>

<p><%= link_to('View All Workouts', workouts_path, class: 'small_button') %></p>
<p><%= link_to("View #{@user.name}'s Workouts", user_workouts_path(@user), class: 'small_button') %></p>
<p><%= link_to('Make Workout', new_user_workout_path(current_user), class: 'small_button') if current_users_profile?(@user) %></p>

<h2><%= @user.name %>'s Saved Workouts: </h2>
<ul>
<% @user.user_saved_workouts.each do |user_saved_workout| %>
  <li>
    <h2><%= link_to(title(user_saved_workout), workout_path(user_saved_workout.saved_workout), class: 'button') %></h2>
    <%= link_to('Edit Saved Workout', edit_workout_user_saved_workout_path(user_saved_workout.saved_workout, user_saved_workout), class: 'small_button') if current_users_saved_workout?(user_saved_workout) %>
    <%= link_to('Unsave', workout_user_saved_workout_path(user_saved_workout.saved_workout, user_saved_workout), method: :delete, class: 'small_button') if current_users_saved_workout?(user_saved_workout) %>
    <p>By: <%= link_to(user_name(user_saved_workout), user_path(user_saved_workout.saved_workout.user)) %></p>
    <p><%= saved_workout_description(user_saved_workout) %></p>
  </li>
<% end %>
</ul>